

import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Navbar() {
  return (<>
    <header className="flex items-center border border-blue-800 h-16">
      <div className="border border-red-800 flex-1 h-full">
        <div className="border border-orange-600"> {/* Perfil Container */}
          <div className="">
            <figure></figure>
          </div>
        </div>
      </div>
      {<nav className="flex-1 border border-orange-400 w-1/2 h-full content-center">
        <Link href="/es" className="hover:bg-neutral-500  border border-transparent text-[15px] p-1.5 pl-[10px] pr-[10px] focus:outline-none rounded-4xl  focus:bg-neutral-500">Inicio</Link> {" "} {/* {""} ----> Genera Espacios */}
        <Link href="/Peliculas" className="hover:bg-neutral-500  border border-transparent text-[15px] p-1.5 pl-2.5 pr-2.5 focus:outline-none rounded-4xl  focus:bg-neutral-500">Películas</Link> {" "}
        <Link href="/Series" className="hover:bg-neutral-500  border border-transparent text-[15px] p-1.5 pl-2.5 pr-2.5 focus:outline-none rounded-4xl  focus:bg-neutral-500"> Series</Link> {" "}
        <Link href="/MiLista" className="hover:bg-neutral-500   border border-transparent text-[15px] p-1.5 pl-2.5 pr-2.5 focus:outline-none rounded-4xl  focus:bg-neutral-500">Mi Lista</Link> {" "}
      </nav>}
      <div className="flex-1 border border-blue-700">

      </div>
    </header></>

  );
}
