
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Inicio ----- ",
  /* description: "Generated by create next app", */
};

export default function Page() {
  return (
    <div className="h-auto border border-blue-600 ">
      <section className="border border-red-500 h-70">
       
      </section>
    </div>
  )
}
