import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_Mono } from "next/font/google";
import Navbar from '@/app/components/Navbar'
import KeyboardNavigation from "./components/KeyboardNavigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoMono = Noto_Sans_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-noto-mono",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" > {/* className={notoMono.variable} */} {/* Poner font globalmente */}
      <body className=" h-auto overflow-y-none">
        <section className="z-0 h-full bottom-0 w-full absolute overflow-y-auto">
          {children}
        </section>
        <Navbar />
        <KeyboardNavigation />
      </body>
    </html>
  );
}
