import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '@/app/components/Navbar'
import KeyboardNavigation from "./components/KeyboardNavigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="es">
      <body className="border border-red-700 h-auto overflow-y-scroll">
        <Navbar />
        <KeyboardNavigation />
        {children}
      </body>
    </html>
  );
}
