import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "New & Popular ",
  /* description: "Generated by create next app", */
};

export default function Page() {
  return (
    <div>
      <h1>New & Popular</h1>
    </div>
  )
}