import type { Metadata } from "next";
import HeroCarousel from "@/app/components/hero/HeroCarousel";


export const metadata: Metadata = {
  title: "Home",
  /* description: "Generated by create next app", */
};

export default function Page() {
  return (
    <>
      <section className="border border-red-500 h-140"> {/* 1 carrucel */}
        <HeroCarousel/>
      </section>
    </>
  )
}